name: pock_audio_player
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: 0.9.32
  google_fonts: 4.0.3
  audio_video_progress_bar: 1.0.1
  just_audio_background: ^0.0.1-beta.9
  audio_service: ^0.18.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/image/capa.jpeg
    - assets/audio/metallica_one.mp3

